name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          pip install -r requirements.txt
          pip install -U .
          
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 --per-file-ignores="__init__.py:F401" .
      - name: Run tests
        run: |
          coverage run --omit=tests/* -m pytest tests
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*